# Generated by Django 5.0.7 on 2024-08-28 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('being_checked', 'На проверке'), ('active', 'Активно'), ('denied', 'Отклонено'), ('archived', 'Архивировано')], default='being_checked', max_length=20),
        ),
    ]
