# Generated by Django 5.1 on 2024-08-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_author_post_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contacts',
        ),
    ]
