# Generated by Django 5.1 on 2024-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_options_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_admins',
            field=models.BooleanField(default=False),
        ),
    ]
