# Generated by Django 5.1 on 2024-09-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinteraction',
            name='reaction',
        ),
    ]
