# Generated by Django 5.1 on 2024-09-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_postinteraction_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostInteraction',
        ),
    ]
