# Generated by Django 5.1 on 2024-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='default_value', max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
