# Generated by Django 5.1 on 2024-09-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_delete_postinteraction'),
        ('user', '0004_telegramprofile_customuser_telegram_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('ip', models.GenericIPAddressField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visited_posts', models.ManyToManyField(blank=True, to='post.post')),
            ],
        ),
    ]
