# Generated by Django 5.1.5 on 2025-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has a premium subscription', verbose_name='Premium Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_started',
            field=models.DateTimeField(blank=True, help_text='The date and time when the premium subscription started', null=True),
        ),
    ]
